version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: winter-social-network-mysql
    ports:
      - 13306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: '12092000'
      MYSQL_DATABASE: winter_social_network
      MYSQL_USER: winter
      MYSQL_PASSWORD: 1
      LANG: C.UTF-8
      TZ: Asia/Ho_Chi_Minh
  
  redis: 
    image: redis:6.2.5
    container_name: winter-social-network-redis
    ports:
      - 16379:6379
    environment:
      LANG: C.UTF-8
      TZ: Asia/Ho_Chi_Minh
